-- Schema for the bakery bot. Written in SQL that both PostgreSQL and H2 in
-- PostgreSQL mode accept, so the database can be swapped without code changes.
-- Only Telegram IDs are stored for customers; no names, no phone numbers.

CREATE TABLE users (
    telegram_id    BIGINT       PRIMARY KEY,
    source         VARCHAR(32)  NOT NULL DEFAULT 'direct',
    first_seen_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    blocked_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE staff (
    telegram_id   BIGINT       PRIMARY KEY,
    role          VARCHAR(16)  NOT NULL,
    display_name  VARCHAR(64)  NOT NULL,
    added_by      BIGINT,
    added_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT staff_role_check CHECK (role IN ('BAKER', 'ADMIN'))
);

CREATE TABLE invites (
    token       VARCHAR(64)  PRIMARY KEY,
    role        VARCHAR(16)  NOT NULL,
    created_by  BIGINT       NOT NULL,
    used_by     BIGINT,
    used_at     TIMESTAMP WITH TIME ZONE,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT invites_role_check CHECK (role IN ('BAKER', 'ADMIN'))
);

CREATE TABLE products (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(64)  NOT NULL,
    description     VARCHAR(512),
    price           NUMERIC(10, 2),
    photo_file_id   VARCHAR(256),
    sort_order      INTEGER      NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_products_active_order ON products (is_active, sort_order);

CREATE TABLE subscriptions (
    user_id     BIGINT  NOT NULL REFERENCES users (telegram_id) ON DELETE CASCADE,
    product_id  BIGINT  NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (user_id, product_id)
);

CREATE INDEX idx_subscriptions_product ON subscriptions (product_id);

CREATE TABLE batches (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT       NOT NULL REFERENCES products (id),
    status              VARCHAR(16)  NOT NULL,
    announced_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    ready_at            TIMESTAMP WITH TIME ZONE,
    closed_at           TIMESTAMP WITH TIME ZONE,
    created_by          BIGINT       NOT NULL,
    channel_message_id  BIGINT,
    control_chat_id     BIGINT,
    control_message_id  BIGINT,
    ready_manually      BOOLEAN      NOT NULL DEFAULT FALSE,
    closed_manually     BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT batches_status_check CHECK (
        status IN ('ANNOUNCED', 'READY', 'SOLD_OUT', 'EXPIRED', 'CANCELLED')
    )
);

-- Lookup of the active batch of a product (duplicate-tap guard) and of the last
-- batch that reached READY (freshness status in the catalogue).
CREATE INDEX idx_batches_product_status ON batches (product_id, status);
CREATE INDEX idx_batches_product_ready  ON batches (product_id, ready_at);

CREATE TABLE batch_messages (
    batch_id    BIGINT  NOT NULL REFERENCES batches (id) ON DELETE CASCADE,
    chat_id     BIGINT  NOT NULL,
    message_id  BIGINT  NOT NULL,
    PRIMARY KEY (batch_id, chat_id)
);

CREATE TABLE going_clicks (
    batch_id     BIGINT       NOT NULL REFERENCES batches (id) ON DELETE CASCADE,
    telegram_id  BIGINT       NOT NULL,
    source       VARCHAR(32)  NOT NULL,
    clicked_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (batch_id, telegram_id)
);

CREATE TABLE daily_stats (
    stat_date         DATE     PRIMARY KEY,
    channel_members   INTEGER,
    bot_active_users  INTEGER  NOT NULL DEFAULT 0,
    new_users         INTEGER  NOT NULL DEFAULT 0,
    left_users        INTEGER  NOT NULL DEFAULT 0
);

-- KEY and VALUE are reserved words in H2, hence the prefixed column names.
CREATE TABLE settings (
    setting_key    VARCHAR(64)  PRIMARY KEY,
    setting_value  VARCHAR(256) NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL
);
